name = "name-gen-v3"
main = "src/index.ts"
compatibility_date = "2024-01-16"

# 变量配置
[vars]
AI_API_ENDPOINT = "https://api.deepseek.com/v1/chat/completions"
ENVIRONMENT = "development"

# 开发环境变量
[env.development]
name = "name-gen-v3-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境变量
[env.production]
name = "name-gen-v3"
vars = { ENVIRONMENT = "production", AI_API_ENDPOINT = "https://api.deepseek.com/v1/chat/completions" }

# 需要通过命令行或者 Cloudflare Dashboard 设置的秘密变量
# wrangler secret put AI_API_KEY
# AI_API_KEY = "your-api-key-here"